export * from './Cart'
export * from './Home'
export * from './Login'
export * from './Laminas'
export * from './Tesouras'
export * from './Maquinas'
export * from './Equipamentos'
export * from './Pentes'
export * from './Register'
export * from './Order'
export * from './Admin/Orders'
export * from './Admin/Products'
export * from './Admin/NewProduct'
export * from './Admin/EditProduct'

